<a href="https://colab.research.google.com/github/Alexsinator/Challenge_Alura_Store_Alex/blob/main/TelecomX_LATAM_Parte_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [7]:
datos = pd.read_csv('/content/datos_tratados.csv')

# Lectura de los datos

In [8]:
datos

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias
0,0002-ORFBO,No,Female,No,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,No,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,No,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,Si,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,Si,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,No,Female,No,No,No,13,Yes,No,DSL,...,No,Yes,No,No,One year,No,Mailed check,55.15,742.90,1.838333
7039,9992-RRAMN,Yes,Male,No,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70,2.836667
7040,9992-UJOEL,No,Male,No,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7041,9993-LHIEB,No,Male,No,Yes,Yes,67,Yes,No,DSL,...,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7042,9995-HOTOH,No,Male,No,Yes,Yes,63,No,No phone service,DSL,...,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60,1.966667

In [3]:
datos.shape

(7043, 22)

In [4]:
datos.describe()

,customer.tenure,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias
count,7043.000000,7043.000000,7032.000000,7043.000000
mean,32.371149,64.761692,2283.300441,2.158723
std,24.559481,30.090047,2266.771362,1.003002
min,0.000000,18.250000,18.800000,0.608333
25%,9.000000,35.500000,401.450000,1.183333
50%,29.000000,70.350000,1397.475000,2.345000
75%,55.000000,89.850000,3794.737500,2.995000
max,72.000000,118.750000,8684.800000,3.958333

In [5]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   object
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   object
 4   customer.Partner           7043 non-null   object
 5   customer.Dependents        7043 non-null   object
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7032 non-null   float64
 21  Cuentas_Diarias            7043 non-null   float64
dtypes: float64(3), int64(1), object(18)
memory usage: 1.2+ MB

## Análisis de los datos

In [19]:
datos['phone.MultipleLines'].value_counts()

phone.MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

In [15]:
datos['internet.InternetService'].value_counts()

internet.InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

In [17]:
datos['internet.OnlineSecurity'].value_counts()

internet.OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

In [18]:
datos['internet.OnlineBackup'].value_counts()

internet.OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

In [20]:
datos['internet.DeviceProtection'].value_counts()

internet.DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

In [21]:
datos['internet.DeviceProtection'].value_counts()

internet.DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

In [22]:
datos['internet.TechSupport'].value_counts()

internet.TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

In [23]:
datos['internet.TechSupport'].value_counts()

internet.TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

In [24]:
datos['internet.StreamingTV'].value_counts()

internet.StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

In [25]:
datos['internet.StreamingMovies'].value_counts()

internet.StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

### Revisión de consistencia de datos

In [30]:
columnas_a_verificar = ['internet.OnlineSecurity', 'internet.OnlineBackup', 'internet.DeviceProtection', 'internet.TechSupport', 'internet.StreamingTV', 'internet.StreamingMovies']
columna_referencia = 'internet.InternetService'

In [36]:
for columna in columnas_a_verificar:
    inconsistencias = (datos[columna_referencia] == 'Yes') & (datos[columna] == 'No internet service')
    if inconsistencias.any():
        print(f"Inconsistencias encontradas en la columna:  {columna}.")
    else:
        print(f"No se encontraron inconsistencias en la columna {columna}.")

No se encontraron inconsistencias en la columna internet.OnlineSecurity.
No se encontraron inconsistencias en la columna internet.OnlineBackup.
No se encontraron inconsistencias en la columna internet.DeviceProtection.
No se encontraron inconsistencias en la columna internet.TechSupport.
No se encontraron inconsistencias en la columna internet.StreamingTV.
No se encontraron inconsistencias en la columna internet.StreamingMovies.

##Tratamiento de los datos

In [37]:
datos.tail(10)

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias
7033,9975-SKRNR,No,Male,No,No,No,1,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,18.90,18.90,0.630000
7034,9978-HYCIN,No,Male,Si,Yes,Yes,47,Yes,No,Fiber optic,...,No,No,Yes,No,One year,Yes,Bank transfer (automatic),84.95,4018.05,2.831667
7035,9979-RGMZT,No,Female,No,No,No,7,Yes,No,Fiber optic,...,No,No,Yes,Yes,One year,Yes,Mailed check,94.05,633.45,3.135000
7036,9985-MWVIX,Yes,Female,No,No,No,1,Yes,No,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Mailed check,70.15,70.15,2.338333
7037,9986-BONCE,Yes,Female,No,No,No,4,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Bank transfer (automatic),20.95,85.50,0.698333
7038,9987-LUTYD,No,Female,No,No,No,13,Yes,No,DSL,...,No,Yes,No,No,One year,No,Mailed check,55.15,742.90,1.838333
7039,9992-RRAMN,Yes,Male,No,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70,2.836667
7040,9992-UJOEL,No,Male,No,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7041,9993-LHIEB,No,Male,No,Yes,Yes,67,Yes,No,DSL,...,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7042,9995-HOTOH,No,Male,No,Yes,Yes,63,No,No phone service,DSL,...,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60,1.966667

In [54]:
# Reemplazos a binarios
datos['Churn'] = datos['Churn'].replace({'No': 0, 'Yes':1})
datos['customer.gender'] = datos['customer.gender'].replace({'Male': 0, 'Female': 1})
datos['customer.SeniorCitizen'] = datos['customer.SeniorCitizen'].replace({'No': 0, 'Si': 1})
datos['customer.Partner'] = datos['customer.Partner'].replace({'No': 0, 'Yes':1})
datos['customer.Dependents'] = datos['customer.Dependents'].replace({'No': 0, 'Yes':1})
datos['phone.PhoneService'] = datos['phone.PhoneService'].replace({'No': 0, 'Yes':1})
datos['account.PaperlessBilling'] = datos['account.PaperlessBilling'].replace({'No': 0, 'Yes':1})

/tmp/ipython-input-929620156.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos['phone.PhoneService'] = datos['phone.PhoneService'].replace({'No': 0, 'Yes':1})
/tmp/ipython-input-929620156.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos['account.PaperlessBilling'] = datos['account.PaperlessBilling'].replace({'No': 0, 'Yes':1})

In [55]:
datos.sample(10)

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias
141,0234-TEVTT,0,1,0,1,1,48,0,No phone service,DSL,...,Yes,No,No,Yes,One year,0,Credit card (automatic),45.00,2196.30,1.500000
2734,3891-NLXJB,0,0,0,0,0,37,0,No phone service,DSL,...,No,Yes,No,No,Two year,1,Mailed check,40.55,1390.85,1.351667
5160,7253-UVNDW,1,1,0,0,0,46,1,No,DSL,...,Yes,Yes,No,No,Two year,0,Credit card (automatic),54.35,2460.15,1.811667
2528,3620-MWJNE,0,0,0,0,0,2,1,No,DSL,...,No,Yes,No,No,Month-to-month,1,Mailed check,54.45,87.30,1.815000
2490,3566-HJGPK,0,0,0,0,0,1,1,No,DSL,...,No,No,No,No,Month-to-month,1,Mailed check,45.55,45.55,1.518333
6322,8949-JTMAY,1,1,0,0,0,29,1,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,1,Credit card (automatic),98.60,2933.20,3.286667
6638,9436-ZBZCT,1,0,0,0,0,14,1,Yes,Fiber optic,...,No,Yes,Yes,No,Month-to-month,1,Electronic check,89.95,1178.40,2.998333
3543,5022-JNQEQ,0,1,0,1,1,9,1,No,Fiber optic,...,No,Yes,No,No,Month-to-month,1,Electronic check,75.85,647.50,2.528333
4198,5928-QLDHB,0,0,0,0,0,9,1,Yes,Fiber optic,...,No,No,No,No,Month-to-month,1,Electronic check,76.25,684.85,2.541667
3081,4415-WNGVR,0,1,1,1,0,12,1,No,DSL,...,Yes,Yes,Yes,Yes,One year,1,Electronic check,79.20,943.85,2.640000

In [50]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   int64
 2   customer.gender            7043 non-null   int64
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   int64
 5   customer.Dependents        7043 non-null   int64
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7032 non-null   float64
 21  Cuentas_Diarias            7043 non-null   float64
dtypes: float64(3), int64(6), object(13)
memory usage: 1.2+ MB

In [56]:
# Hacer categoricas a númericas
categoricas = ['account.PaymentMethod', 'phone.MultipleLines', 'internet.InternetService', 'internet.OnlineSecurity',
               'internet.OnlineBackup', 'internet.DeviceProtection', 'internet.TechSupport', 'internet.StreamingTV',
               'internet.StreamingMovies', 'account.Contract']

In [59]:
datos_categorizados = pd.get_dummies(datos, columns=categoricas, dtype = int)

In [60]:
datos_categorizados.sample(10)

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,account.PaperlessBilling,account.Charges.Monthly,...,internet.TechSupport_Yes,internet.StreamingTV_No,internet.StreamingTV_No internet service,internet.StreamingTV_Yes,internet.StreamingMovies_No,internet.StreamingMovies_No internet service,internet.StreamingMovies_Yes,account.Contract_Month-to-month,account.Contract_One year,account.Contract_Two year
5693,8020-BWHYL,1,1,1,0,0,15,1,1,75.30,...,0,1,0,0,1,0,0,1,0,0
63,0107-WESLM,1,0,0,0,0,1,1,1,19.85,...,0,0,1,0,0,1,0,1,0,0
1079,1571-SAVHK,1,0,0,0,0,12,1,1,99.95,...,1,0,0,1,0,0,1,1,0,0
3751,5286-YHCVC,0,0,0,1,0,72,1,1,104.80,...,0,0,0,1,0,0,1,0,0,1
2074,2984-AFWNC,0,1,0,0,0,3,1,0,95.40,...,0,0,0,1,0,0,1,1,0,0
3659,5171-EPLKN,0,0,0,0,0,27,1,0,19.85,...,0,0,1,0,0,1,0,0,0,1
1718,2506-CLAKW,1,1,0,0,0,6,1,1,98.15,...,1,1,0,0,0,0,1,1,0,0
5074,7131-ZQZNK,0,1,0,1,1,60,0,0,59.85,...,1,0,0,1,0,0,1,0,0,1
5390,7601-WFVZV,0,0,0,0,0,1,1,0,19.55,...,0,0,1,0,0,1,0,1,0,0
3732,5248-RPYWW,0,1,1,1,1,72,1,1,90.15,...,1,0,0,1,0,0,1,0,0,1